'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("hello.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _123() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_123", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property ball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property bgm() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bgm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property Cubic_11_1_100_R() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Cubic_11_1_100_R", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property esc背景圖片() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("esc背景圖片", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_arrow_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_arrow_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_arrow_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_arrow_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_bulbasaur_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_bulbasaur_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_bulbasaur_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_bulbasaur_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_charmander_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_charmander_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_charmander_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_charmander_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_fire_icon_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_fire_icon_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_pikachu_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_pikachu_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_pikachu_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_pikachu_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_score_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_score_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_score_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_score_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_score_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_score_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_scoreboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_scoreboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_squirtle_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_squirtle_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_squirtle_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_squirtle_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_strength() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_strength", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_thunder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_thunder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_vine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_vine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property game_vine_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_vine_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property stick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property VT323_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VT323_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property WAVE140_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WAVE140_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property WAVE141_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WAVE141_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property WAVE142_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WAVE142_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property WAVE143_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WAVE143_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property WAVE144_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WAVE144_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property WAVE145_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WAVE145_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property WAVE146_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WAVE146_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 傑尼龜() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("傑尼龜", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 傑尼龜1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("傑尼龜1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 妙蛙種子() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("妙蛙種子", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 妙蛙種子1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("妙蛙種子1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 小圖示() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小圖示", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 小火龍() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小火龍", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 小火龍1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小火龍1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 打球背景2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("打球背景2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 技能施放提示() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("技能施放提示", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 皮卡丘() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("皮卡丘", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 皮卡丘1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("皮卡丘1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 皮卡丘封面() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("皮卡丘封面", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 設定背景圖片() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("設定背景圖片", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 遊戲旗桿() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("遊戲旗桿", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 遊戲背景() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("遊戲背景", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
